# Generated by Django 5.1.6 on 2025-03-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_news_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_ed'], 'verbose_name': 'NEW', 'verbose_name_plural': 'NEWS'},
        ),
    ]
