# Generated by Django 5.1.6 on 2025-03-12 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_ed'], 'verbose_name': 'NEW', 'verbose_name_plural': 'NEWS'},
        ),
    ]
