# Generated by Django 5.1.6 on 2025-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0005_alter_news_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photo',
        ),
        migrations.AddField(
            model_name='news',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='media/photos/'),
        ),
    ]
