# Generated by Django 5.1.6 on 2025-03-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0006_remove_news_photo_news_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photos',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
