# Generated by Django 5.1.6 on 2025-03-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0008_alter_news_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photos',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
