# Generated by Django 5.1.6 on 2025-03-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0009_alter_news_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='videos/'),
        ),
    ]
